import { Geist, Geist_Mono, Inter } from "next/font/google";
import ThemeProvider from "@/providers/ThemeProvider";
import "./globals.css";
import NextThemeProvider from "@/providers/NextThemeProvider";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextThemeProvider>
        <ThemeProvider>
          {children}
        </ThemeProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
